# Exclude third-party libraries
engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - php
        - css
        - javascript
ratings:
  paths:
  - "**.php"
  - "**.css"
  - "**.js"
exclude_paths:
- htdocs/includes/Zend/**
- htdocs/includes/htmlpurifier/**
- htdocs/includes/phpxmlrpc/**
- htdocs/includes/phpmailer/**
- htdocs/includes/magpierss/**
- htdocs/includes/simplepie.inc.php
- htdocs/js/jquery.*.js
- htdocs/includes/sphinxapi.php
- htdocs/js/scriptaculous/**
- htdocs/js/flowplayer-6.0.5/**
- htdocs/admin/apc.php
- htdocs/admin/memcache.php
