# Exclude third-party libraries
engines:
  phpmd:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        -php
exclude_paths:
- htdocs/includes/Zend/
- htdocs/includes/htmlpurifier/
- htdocs/includes/phpxmlrpc/
- htdocs/includes/phpmailer/
- htdocs/includes/magpierss/
- htdocs/js/scriptaculous/
- htdocs/js/flowplayer-6.0.5/
