name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Node dependencies
      run: cd htdocs/js/vendor && npm install && npm run build && cd ../../..

    # - name: Run test suite
    #   run: composer run-script test

  deploy:
    name: Gated deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Specify filesystem path, per branch
      run: ./deploy/branch_deploy.sh
    
    - name: Populate various files with secrets
      run: ./deploy/config_variables.sh
    
    - name: Save AWS credentials
      run: ./deploy/aws_credentials.sh

    - name: Bundle files for deployment
      run: zip -qr rs-web-deploy . --exclude *.git* *.scannerwork* && mkdir -p upload && mv rs-web-deploy.zip upload/rs-web-deploy.zip
